package report

import (
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/unidoc/unipdf/v3/common/license"
	"github.com/unidoc/unipdf/v3/creator"
	"github.com/unidoc/unipdf/v3/model"

	"github.com/unidoc/unisupply/internal/version"
	"github.com/unidoc/unisupply/pkg/resolver"
	"github.com/unidoc/unisupply/pkg/scanner"
	"github.com/unidoc/unisupply/pkg/scorer"
)

// PDFOptions configures PDF report generation.
type PDFOptions struct {
	OutputPath string
	GoVersion  string
	CIReport   *scanner.CIReport
	Takeovers  []*scanner.MaintainerInfo
}

// WritePDF generates an enterprise-grade PDF risk report using UniPDF.
func WritePDF(graph *resolver.Graph, ps *scorer.ProjectScore, opts PDFOptions) error {
	// Set UniPDF license (metered/API key from env, or unlicensed for open source).
	if err := initLicense(); err != nil {
		// Continue without license — will have watermark.
		_ = err
	}

	c := creator.New()
	c.SetPageSize(creator.PageSizeLetter)
	c.SetPageMargins(50, 50, 50, 50)

	// Register fonts.
	helvetica, _ := model.NewStandard14Font(model.HelveticaName)
	helveticaBold, _ := model.NewStandard14Font(model.HelveticaBoldName)

	// Footer on every page.
	c.DrawFooter(func(block *creator.Block, args creator.FooterFunctionArgs) {
		p := c.NewStyledParagraph()
		chunk := p.Append(fmt.Sprintf("Generated by unisupply v%s — unidoc.io/unisupply  |  Page %d of %d", version.String(), args.PageNum, args.TotalPages))
		chunk.Style.Font = helvetica
		chunk.Style.FontSize = 8
		chunk.Style.Color = creator.ColorRGBFromHex("#888888")
		p.SetTextAlignment(creator.TextAlignmentCenter)
		_ = block.Draw(p)
	})

	// === Page 1: Cover Page ===
	writeCoverPage(c, graph, ps, helvetica, helveticaBold)

	// === Page 2: Executive Summary ===
	writeExecutiveSummary(c, graph, ps, opts, helvetica, helveticaBold)

	// === Page 3+: Critical Risk Dependencies ===
	writeCriticalRiskSection(c, ps, helvetica, helveticaBold)

	// === High Risk Dependencies ===
	writeHighRiskSection(c, ps, helvetica, helveticaBold)

	// === Medium Risk Dependencies ===
	writeMediumRiskSection(c, ps, helvetica, helveticaBold)

	// === Low Risk Dependencies ===
	writeLowRiskSection(c, ps, helvetica, helveticaBold)

	// === CI/CD Risk Assessment (if available) ===
	if opts.CIReport != nil && len(opts.CIReport.Workflows) > 0 {
		writeCISection(c, opts.CIReport, helvetica, helveticaBold)
	}

	// === Takeover Candidates (if any) ===
	if len(opts.Takeovers) > 0 {
		writeTakeoverSection(c, opts.Takeovers, helvetica, helveticaBold)
	}

	// === Methodology ===
	writeMethodologyPage(c, helvetica, helveticaBold)

	outputPath := opts.OutputPath
	if outputPath == "" {
		outputPath = "unisupply-report.pdf"
	}

	return c.WriteToFile(outputPath)
}

func initLicense() error {
	// Try metered API key from environment.
	// If not set, UniPDF will run in demo mode with watermark.
	return license.SetMeteredKey(os.Getenv("UNIDOC_LICENSE_API_KEY"))
}

func writeCoverPage(c *creator.Creator, graph *resolver.Graph, ps *scorer.ProjectScore, regular, bold *model.PdfFont) {
	c.NewPage()

	// Title.
	title := c.NewStyledParagraph()
	titleChunk := title.Append("Go Supply Chain\nRisk Assessment")
	titleChunk.Style.Font = bold
	titleChunk.Style.FontSize = 36
	titleChunk.Style.Color = creator.ColorRGBFromHex("#1a1a2e")
	title.SetTextAlignment(creator.TextAlignmentCenter)
	title.SetMargins(0, 0, 150, 30)
	_ = c.Draw(title)

	// Divider line.
	line := c.NewStyledParagraph()
	lineChunk := line.Append(strings.Repeat("━", 50))
	lineChunk.Style.Font = regular
	lineChunk.Style.FontSize = 12
	lineChunk.Style.Color = creator.ColorRGBFromHex("#0066cc")
	line.SetTextAlignment(creator.TextAlignmentCenter)
	_ = c.Draw(line)

	// Project name.
	project := c.NewStyledParagraph()
	pChunk := project.Append(graph.Root)
	pChunk.Style.Font = regular
	pChunk.Style.FontSize = 18
	pChunk.Style.Color = creator.ColorRGBFromHex("#333333")
	project.SetTextAlignment(creator.TextAlignmentCenter)
	project.SetMargins(0, 0, 20, 10)
	_ = c.Draw(project)

	// Overall risk score — large indicator.
	scoreColor := pdfRiskColor(ps.OverallLevel)
	scorePara := c.NewStyledParagraph()
	sChunk := scorePara.Append(fmt.Sprintf("Overall Risk Score: %d/100 (%s)", ps.OverallScore, ps.OverallLevel))
	sChunk.Style.Font = bold
	sChunk.Style.FontSize = 24
	sChunk.Style.Color = scoreColor
	scorePara.SetTextAlignment(creator.TextAlignmentCenter)
	scorePara.SetMargins(0, 0, 40, 20)
	_ = c.Draw(scorePara)

	// Date.
	datePara := c.NewStyledParagraph()
	dChunk := datePara.Append(time.Now().UTC().Format("January 2, 2006"))
	dChunk.Style.Font = regular
	dChunk.Style.FontSize = 14
	dChunk.Style.Color = creator.ColorRGBFromHex("#666666")
	datePara.SetTextAlignment(creator.TextAlignmentCenter)
	datePara.SetMargins(0, 0, 10, 0)
	_ = c.Draw(datePara)

	// Branding.
	branding := c.NewStyledParagraph()
	bChunk := branding.Append("Built by UniDoc — Enterprise Go Platform\nunidoc.io")
	bChunk.Style.Font = regular
	bChunk.Style.FontSize = 12
	bChunk.Style.Color = creator.ColorRGBFromHex("#0066cc")
	branding.SetTextAlignment(creator.TextAlignmentCenter)
	branding.SetMargins(0, 0, 100, 0)
	_ = c.Draw(branding)
}

func writeExecutiveSummary(c *creator.Creator, graph *resolver.Graph, ps *scorer.ProjectScore, opts PDFOptions, regular, bold *model.PdfFont) {
	c.NewPage()

	heading(c, "Executive Summary", bold)

	directCount := graph.DirectCount()
	transitiveCount := graph.TransitiveCount()
	total := directCount + transitiveCount

	// Key metrics table.
	table := c.NewTable(2)
	table.SetMargins(0, 0, 10, 20)
	err := table.SetColumnWidths(0.4, 0.6)
	if err != nil {
		fmt.Printf("Error setting column widths: %v\n", err)
		return
	}

	addTableRow(c, table, "Project", graph.Root, regular, bold)
	addTableRow(c, table, "Go Version", opts.GoVersion, regular, bold)
	addTableRow(c, table, "Direct Dependencies", fmt.Sprintf("%d", directCount), regular, bold)
	addTableRow(c, table, "Transitive Dependencies", fmt.Sprintf("%d", transitiveCount), regular, bold)
	addTableRow(c, table, "Total Dependencies", fmt.Sprintf("%d", total), regular, bold)
	addTableRow(c, table, "Overall Risk Score", fmt.Sprintf("%d/100 (%s)", ps.OverallScore, ps.OverallLevel), regular, bold)
	_ = c.Draw(table)

	// Risk distribution.
	subheading(c, "Risk Distribution", bold)

	distTable := c.NewTable(3)
	distTable.SetMargins(0, 0, 5, 15)
	if err = distTable.SetColumnWidths(0.4, 0.3, 0.3); err != nil {
		fmt.Printf("Error setting column widths: %v\n", err)
		return
	}

	addTableHeader(c, distTable, []string{"Risk Level", "Count", "Percentage"}, bold)
	addTableRow3(c, distTable, "Critical (76-100)", fmt.Sprintf("%d", ps.CriticalRiskCount), pctStr(ps.CriticalRiskCount, total), regular)
	addTableRow3(c, distTable, "High (51-75)", fmt.Sprintf("%d", ps.HighRiskCount), pctStr(ps.HighRiskCount, total), regular)
	addTableRow3(c, distTable, "Medium (26-50)", fmt.Sprintf("%d", ps.MediumRiskCount), pctStr(ps.MediumRiskCount, total), regular)
	addTableRow3(c, distTable, "Low (0-25)", fmt.Sprintf("%d", ps.LowRiskCount), pctStr(ps.LowRiskCount, total), regular)
	_ = c.Draw(distTable)

	// Vulnerability summary.
	subheading(c, "Key Findings", bold)

	findings := c.NewStyledParagraph()
	findings.SetMargins(0, 0, 5, 0)
	findings.SetLineHeight(1.6)
	addBullet(findings, fmt.Sprintf("Total vulnerabilities found: %d", ps.TotalVulns), regular)
	addBullet(findings, fmt.Sprintf("Unmaintained dependencies (>2yr): %d", ps.Unmaintained2yr), regular)
	addBullet(findings, fmt.Sprintf("Unmaintained dependencies (>1yr): %d", ps.Unmaintained1yr), regular)
	_ = c.Draw(findings)
}

// filterRiskBucket returns dependencies whose RiskScore is in [min, max).
// A max of 0 means "no upper bound".
func filterRiskBucket(deps []*scorer.DependencyScore, min, max int) []*scorer.DependencyScore {
	var out []*scorer.DependencyScore
	for _, ds := range deps {
		if ds.RiskScore < min {
			continue
		}
		if max > 0 && ds.RiskScore >= max {
			continue
		}
		out = append(out, ds)
	}
	return out
}

func writeCriticalRiskSection(c *creator.Creator, ps *scorer.ProjectScore, regular, bold *model.PdfFont) {
	critRisk := filterRiskBucket(ps.Dependencies, 76, 0)

	if len(critRisk) == 0 {
		return
	}

	c.NewPage()
	heading(c, fmt.Sprintf("Critical Risk Dependencies (%d)", len(critRisk)), bold)

	for _, ds := range critRisk {
		writeDependencyBlock(c, ds, regular, bold, true)
	}
}

func writeHighRiskSection(c *creator.Creator, ps *scorer.ProjectScore, regular, bold *model.PdfFont) {
	highRisk := filterRiskBucket(ps.Dependencies, 51, 76)

	if len(highRisk) == 0 {
		return
	}

	c.NewPage()
	heading(c, fmt.Sprintf("High Risk Dependencies (%d)", len(highRisk)), bold)

	for _, ds := range highRisk {
		writeDependencyBlock(c, ds, regular, bold, true)
	}
}

func writeMediumRiskSection(c *creator.Creator, ps *scorer.ProjectScore, regular, bold *model.PdfFont) {
	medRisk := filterRiskBucket(ps.Dependencies, 26, 51)

	if len(medRisk) == 0 {
		return
	}

	c.NewPage()
	heading(c, fmt.Sprintf("Medium Risk Dependencies (%d)", len(medRisk)), bold)

	// Condensed table format.
	table := c.NewTable(4)
	table.SetMargins(0, 0, 10, 10)
	if err := table.SetColumnWidths(0.45, 0.2, 0.15, 0.2); err != nil {
		fmt.Printf("Error setting column widths: %v\n", err)
		return
	}

	addTableHeader(c, table, []string{"Module", "Version", "Score", "Risk Factors"}, bold)

	for _, ds := range medRisk {
		factors := strings.Join(ds.RiskFactors, ", ")
		if factors == "" {
			factors = "-"
		}
		addTableRow4(c, table, ds.Module, ds.Version, fmt.Sprintf("%d/100", ds.RiskScore), factors, regular)
	}

	_ = c.Draw(table)
}

func writeLowRiskSection(c *creator.Creator, ps *scorer.ProjectScore, regular, bold *model.PdfFont) {
	lowRisk := filterRiskBucket(ps.Dependencies, 0, 26)

	if len(lowRisk) == 0 {
		return
	}

	c.NewPage()
	heading(c, fmt.Sprintf("Low Risk Dependencies (%d)", len(lowRisk)), bold)

	// Summary table.
	table := c.NewTable(3)
	table.SetMargins(0, 0, 10, 10)
	if err := table.SetColumnWidths(0.55, 0.25, 0.2); err != nil {
		fmt.Printf("Error setting column widths: %v\n", err)
		return
	}

	addTableHeader(c, table, []string{"Module", "Version", "Score"}, bold)

	for _, ds := range lowRisk {
		addTableRow3(c, table, ds.Module, ds.Version, fmt.Sprintf("%d/100", ds.RiskScore), regular)
	}

	_ = c.Draw(table)
}

func writeCISection(c *creator.Creator, ciReport *scanner.CIReport, regular, bold *model.PdfFont) {
	c.NewPage()
	heading(c, "CI/CD Risk Assessment", bold)

	// Overall CI score.
	scorePara := c.NewStyledParagraph()
	scorePara.SetMargins(0, 0, 5, 15)
	chunk := scorePara.Append(fmt.Sprintf("CI/CD Risk Score: %d/100 (%s)", ciReport.OverallScore, ciReport.OverallLevel))
	chunk.Style.Font = bold
	chunk.Style.FontSize = 14
	chunk.Style.Color = pdfRiskColor(scorer.RiskLevel(ciReport.OverallLevel))
	_ = c.Draw(scorePara)

	// Summary stats.
	stats := c.NewStyledParagraph()
	stats.SetLineHeight(1.6)
	addBullet(stats, fmt.Sprintf("Unpinned actions: %d", ciReport.UnpinnedActions), regular)
	addBullet(stats, fmt.Sprintf("Third-party actions: %d", ciReport.ThirdPartyActions), regular)
	addBullet(stats, fmt.Sprintf("Total findings: %d", ciReport.TotalFindings), regular)
	_ = c.Draw(stats)

	// Per-workflow breakdown.
	for _, wr := range ciReport.Workflows {
		subheading(c, fmt.Sprintf("Workflow: %s", wr.Name), bold)

		if len(wr.Findings) == 0 {
			p := c.NewStyledParagraph()
			ch := p.Append("No issues found.")
			ch.Style.Font = regular
			ch.Style.FontSize = 10
			_ = c.Draw(p)
			continue
		}

		table := c.NewTable(3)
		table.SetMargins(0, 0, 5, 10)
		if err := table.SetColumnWidths(0.2, 0.5, 0.3); err != nil {
			fmt.Printf("Error setting column widths: %v\n", err)
			return
		}
		addTableHeader(c, table, []string{"Severity", "Description", "Remediation"}, bold)

		for _, f := range wr.Findings {
			addTableRow3(c, table, string(f.Severity), f.Description, f.Remediation, regular)
		}

		_ = c.Draw(table)
	}
}

func writeTakeoverSection(c *creator.Creator, takeovers []*scanner.MaintainerInfo, regular, bold *model.PdfFont) {
	c.NewPage()
	heading(c, "Packages Eligible for Maintenance Takeover", bold)

	intro := c.NewStyledParagraph()
	intro.SetMargins(0, 0, 5, 15)
	ch := intro.Append("The following dependencies are candidates for stewardship — they are widely used but lack active maintenance. Consider adopting or forking these packages.")
	ch.Style.Font = regular
	ch.Style.FontSize = 10
	_ = c.Draw(intro)

	table := c.NewTable(4)
	table.SetMargins(0, 0, 5, 10)
	if err := table.SetColumnWidths(0.35, 0.15, 0.2, 0.3); err != nil {
		fmt.Printf("Error setting column widths: %v\n", err)
		return
	}
	addTableHeader(c, table, []string{"Repository", "Stars", "Activity", "Reason"}, bold)

	for _, t := range takeovers {
		addTableRow4(c, table,
			fmt.Sprintf("%s/%s", t.Owner, t.Repo),
			fmt.Sprintf("%d", t.Stars),
			t.ActivityPattern,
			t.TakeoverReason,
			regular,
		)
	}

	_ = c.Draw(table)
}

func writeMethodologyPage(c *creator.Creator, regular, bold *model.PdfFont) {
	c.NewPage()
	heading(c, "Methodology", bold)

	content := []struct {
		title string
		body  string
	}{
		{"Risk Scoring", "Each dependency receives a score from 0-100 based on weighted factors: known vulnerabilities (40%), maintenance freshness (25%), dependency depth (15%), maintainer risk (10%), and module maturity (10%)."},
		{"Vulnerability Scanning", "Dependencies are checked against the Go Vulnerability Database (vuln.go.dev) for known CVEs and security advisories."},
		{"Maintenance Assessment", "Module release history is obtained from the Go Module Proxy (proxy.golang.org). Archived and deprecated modules receive higher risk scores."},
		{"Maintainer Analysis", "For GitHub-hosted modules, contributor data is analyzed to determine bus factor and activity patterns."},
		{"CI/CD Assessment", "GitHub Actions workflows, Dockerfiles, and build scripts are analyzed for security misconfigurations including unpinned actions, excessive permissions, and dangerous command patterns."},
		{"Risk Levels", "LOW (0-25): Minimal risk, well-maintained. MEDIUM (26-50): Some concerns, monitor. HIGH (51-75): Significant risk, action recommended. CRITICAL (76-100): Immediate action required."},
	}

	for _, section := range content {
		subheading(c, section.title, bold)
		p := c.NewStyledParagraph()
		p.SetMargins(0, 0, 2, 10)
		p.SetLineHeight(1.5)
		ch := p.Append(section.body)
		ch.Style.Font = regular
		ch.Style.FontSize = 10
		_ = c.Draw(p)
	}

	// Contact info.
	contact := c.NewStyledParagraph()
	contact.SetMargins(0, 0, 30, 0)
	ch := contact.Append("For enterprise analysis, ongoing monitoring, or custom reports:\nsecurity@unidoc.io | security.unidoc.io")
	ch.Style.Font = bold
	ch.Style.FontSize = 11
	ch.Style.Color = creator.ColorRGBFromHex("#0066cc")
	contact.SetTextAlignment(creator.TextAlignmentCenter)
	_ = c.Draw(contact)
}

// Helper functions for PDF generation.

func heading(c *creator.Creator, text string, bold *model.PdfFont) {
	p := c.NewStyledParagraph()
	ch := p.Append(text)
	ch.Style.Font = bold
	ch.Style.FontSize = 20
	ch.Style.Color = creator.ColorRGBFromHex("#1a1a2e")
	p.SetMargins(0, 0, 0, 15)
	_ = c.Draw(p)
}

func subheading(c *creator.Creator, text string, bold *model.PdfFont) {
	p := c.NewStyledParagraph()
	ch := p.Append(text)
	ch.Style.Font = bold
	ch.Style.FontSize = 13
	ch.Style.Color = creator.ColorRGBFromHex("#333333")
	p.SetMargins(0, 0, 10, 5)
	_ = c.Draw(p)
}

func addBullet(p *creator.StyledParagraph, text string, font *model.PdfFont) {
	chunk := p.Append("  • " + text + "\n")
	chunk.Style.Font = font
	chunk.Style.FontSize = 10
}

func addTableHeader(cr *creator.Creator, table *creator.Table, headers []string, bold *model.PdfFont) {
	for _, h := range headers {
		cell := table.NewCell()
		cell.SetBackgroundColor(creator.ColorRGBFromHex("#1a1a2e"))
		p := cr.NewStyledParagraph()
		ch := p.Append(h)
		ch.Style.Font = bold
		ch.Style.FontSize = 9
		ch.Style.Color = creator.ColorWhite
		if err := cell.SetContent(p); err != nil {
			fmt.Printf("Error setting table header content: %v\n", err)
		}
	}
}

func addTableRow(cr *creator.Creator, table *creator.Table, label, value string, regular, bold *model.PdfFont) {
	labelCell := table.NewCell()
	lp := cr.NewStyledParagraph()
	lch := lp.Append(label)
	lch.Style.Font = bold
	lch.Style.FontSize = 10
	if err := labelCell.SetContent(lp); err != nil {
		fmt.Printf("Error setting table cell content: %v\n", err)
	}

	valueCell := table.NewCell()
	vp := cr.NewStyledParagraph()
	vch := vp.Append(value)
	vch.Style.Font = regular
	vch.Style.FontSize = 10
	if err := valueCell.SetContent(vp); err != nil {
		fmt.Printf("Error setting table cell content: %v\n", err)
	}
}

func addTableRow3(cr *creator.Creator, table *creator.Table, c1, c2, c3 string, font *model.PdfFont) {
	for _, val := range []string{c1, c2, c3} {
		cell := table.NewCell()
		p := cr.NewStyledParagraph()
		ch := p.Append(val)
		ch.Style.Font = font
		ch.Style.FontSize = 9
		if err := cell.SetContent(p); err != nil {
			fmt.Printf("Error setting table cell content: %v\n", err)
		}
	}
}

func addTableRow4(cr *creator.Creator, table *creator.Table, c1, c2, c3, c4 string, font *model.PdfFont) {
	for _, val := range []string{c1, c2, c3, c4} {
		cell := table.NewCell()
		p := cr.NewStyledParagraph()
		ch := p.Append(val)
		ch.Style.Font = font
		ch.Style.FontSize = 9
		if err := cell.SetContent(p); err != nil {
			fmt.Printf("Error setting table cell content: %v\n", err)
		}
	}
}

func writeDependencyBlock(c *creator.Creator, ds *scorer.DependencyScore, regular, bold *model.PdfFont, detailed bool) {
	color := pdfRiskColor(ds.RiskLevel)

	// Module header.
	header := c.NewStyledParagraph()
	header.SetMargins(0, 0, 5, 3)
	ch := header.Append(fmt.Sprintf("%s %s — Risk: %d/100", ds.Module, ds.Version, ds.RiskScore))
	ch.Style.Font = bold
	ch.Style.FontSize = 11
	ch.Style.Color = color
	_ = c.Draw(header)

	if !detailed {
		return
	}

	details := c.NewStyledParagraph()
	details.SetMargins(20, 0, 0, 10)
	details.SetLineHeight(1.5)

	// Vulnerabilities.
	for _, v := range ds.Vulns {
		aliases := strings.Join(v.Aliases, ", ")
		addBullet(details, fmt.Sprintf("Vulnerability: %s (%s) — %s", v.ID, v.Severity, aliases), regular)
		if v.FixedVersion != "" {
			addBullet(details, fmt.Sprintf("  Fix available: %s", v.FixedVersion), regular)
		}
	}

	// Maintenance.
	if ds.Maintenance != nil {
		if ds.Maintenance.MonthsSinceRelease > 0 {
			addBullet(details, fmt.Sprintf("Last release: %d months ago", ds.Maintenance.MonthsSinceRelease), regular)
		}
		if ds.Maintenance.Archived {
			addBullet(details, "Repository archived", regular)
		}
		if ds.Maintenance.Deprecated {
			addBullet(details, "Module deprecated", regular)
		}
	}

	// Risk factors.
	if len(ds.RiskFactors) > 0 {
		addBullet(details, fmt.Sprintf("Risk factors: %s", strings.Join(ds.RiskFactors, ", ")), regular)
	}

	// Dependency path.
	if len(ds.DependencyPath) > 0 {
		addBullet(details, fmt.Sprintf("Used by: %s", strings.Join(ds.DependencyPath, " → ")), regular)
	}

	_ = c.Draw(details)
}

func pdfRiskColor(level scorer.RiskLevel) creator.Color {
	switch level {
	case scorer.RiskCritical:
		return creator.ColorRGBFromHex("#cc0000")
	case scorer.RiskHigh:
		return creator.ColorRGBFromHex("#e67300")
	case scorer.RiskMedium:
		return creator.ColorRGBFromHex("#ccaa00")
	default:
		return creator.ColorRGBFromHex("#009900")
	}
}

func pctStr(count, total int) string {
	if total == 0 {
		return "0%"
	}
	return fmt.Sprintf("%.1f%%", float64(count)/float64(total)*100)
}
